name: Sync dev to staging

on:
  push:
    branches:
      - dev

jobs:
  push-to-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup GitHub CLI
        run: |
          sudo apt install gh -y

      - name: Authenticate GH CLI
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
        run: |
          gh auth login --with-token <<< "$GH_TOKEN"

      - name: Push dev to staging
        run: |
          git checkout staging
          git merge dev --no-ff -m "Auto-merge from dev to staging"
          git push https://x-access-token:${{ secrets.ACTIONS_DEPLOY_TOKEN }}@github.com/${{ github.repository }} staging

