name: Push_to_production

on:
  push:
    branches:  
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
        IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/rf-mlflow-notebook
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MLflow 
        run: pip install mlflow==2.22.0

      - name: Download model artifact from DagsHub
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/G1ul1o/Exercice_DVC.mlflow
 
        run: |
              python -c '
              import mlflow
              import os

              tracking_uri = os.environ["MLFLOW_TRACKING_URI"]
              client = mlflow.tracking.MlflowClient(tracking_uri=tracking_uri)
              experiment_name = 'RandomForestExperiment_2'  # ou le nom de ton expérience
              experiment = client.get_experiment_by_name(experiment_name)
              if experiment is None:
                  raise Exception(f'Experiment {experiment_name} not found')
              runs = client.search_runs(experiment_ids=[experiment.experiment_id], order_by=['attributes.start_time DESC'], max_results=1)
              if not runs:
                  raise Exception('No runs found')
              run_id = runs[0].info.run_id
              print(f'Latest run_id: {run_id}')
              os.system(f'mkdir -p models/rf_model')
              os.system(f'mlflow artifacts download --run-id {run_id} --artifact-path model/rf_model.pkl -o models/rf_model')
              '


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build the image
        run: |
          docker build -t $IMAGE_NAME:application_mflow .

      - name: Push images to Docker Hub
        run: |
          docker push $IMAGE_NAME:application_mflow
