name: Sync staging to production

on:
  workflow_dispatch:
  push:
    branches: [staging]


jobs:
  push-to-production:
    runs-on: ubuntu-latest

    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
     
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install and Build App
        run: |
          cd frontend
          npm install
          npm ci
          npm run test
          npm run build
      
      - name: Setup MLflow 
        run: pip install mlflow==2.22.0

      - name: Download model artifact from DagsHub
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/G1ul1o/Project-Devops.mlflow
 
        run: |
              python -c '
              import mlflow
              import os
              tracking_uri = os.environ["MLFLOW_TRACKING_URI"]
              client = mlflow.tracking.MlflowClient(tracking_uri=tracking_uri)
              experiment_name = "Project_Devops_Mlops"  # ou le nom de ton expérience
              experiment = client.get_experiment_by_name(experiment_name)
              if experiment is None:
                  raise Exception(f"Experiment {experiment_name} not found")
              runs = client.search_runs(experiment_ids=[experiment.experiment_id], order_by=["attributes.start_time DESC"], max_results=1)
              if not runs:
                  raise Exception("No runs found")
              run_id = runs[0].info.run_id
              print(f"Latest run_id: {run_id}")
              os.makedirs("model", exist_ok=True)
              os.system(f"mlflow artifacts download --run-id {run_id} --artifact-path model/XGBClassifier.pkl --dst-path model")
              os.system(f"mlflow artifacts download --run-id {run_id} --artifact-path model/LabelEncoderHeroType.pkl --dst-path model")
              '
      - name: Move model file to clean path
        run: |
            mv model/model/XGBClassifier.pkl backend/XGBClassifier.pkl
            mv model/model/LabelEncoderHeroType.pkl backend/LabelEncoderHeroType.pkl
      
      - name: Install backend dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Install wait-on (for Cypress)
        run: npm install -g wait-on

      - name: Start backend in background
        run: |
          cd backend
          nohup uvicorn server:app --host 127.0.0.1 --port 8000 &

          - name: Wait for backend to be ready
            run: wait-on http://127.0.0.1:8000/docs
    
          - name: Run Cypress E2E tests
            run: npx cypress run
      
      - name: Push staging to production
        env:
            TOKEN: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
        run: |
            git checkout production
            git merge staging --no-ff -m "Auto-merge from staging to production" 
            git push origin production

      - name: Trigger sync-staging-to-production workflow
        env:
          GH_TOKEN: ${{ secrets.TOKEN_ACTIONS }}
        run: |

          gh workflow run push_to_production.yml --ref production
