name: Sync staging to production

on:
  workflow_dispatch:
  push:
    branches: [staging]


jobs:
  push-to-production:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
     
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install and Build App
        run: |
          npm install
          npm ci
          npm run test
          npm run build
      - name: Push staging to production
        env:
            TOKEN: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
        run: |
            git checkout production
            git merge staging  --no-ff -m "Auto-merge from staging to production"
            git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} production
